### ISSUE TITLE
Midifile Tempo

### ISSUE THREAD

**Issue by caseybasichis** [meshula/LabMidi#1]
Hi,
I'm looking to use LabMidi on iOS.

I don't need input or output.

My interest is file in and out with the ability to add Tempo, Timesignatures and controllers.  Is this possible in LabMidi?

Thanks,
Casey

**Comment by meshula** [comment]
The MidiSong class can be used to read a standard MIDI file. It does not have the ability to write one. Writing could be implemented without too much trouble I think.

The MidiSong class lets you specify a starting tempo, but if the MIDI file specifies its own tempo, that tempo will override the starting tempo. You can modify the time signature overall by modifying the ticksPerBeat value.

The MidiSong contains MidiTracks, which are vectors of MidiEvents. The MidiEvents can have controller change instructions. It is up to you what to do with the controller values in those events.

You could write a program to go through each track and modify the controllers.

**Comment by meshula** [comment]
Closing due to 7 years
